### ISSUE TITLE
vot-toolkit ?

### ISSUE THREAD

**Issue by eilo1234** [iiau-tracker/SPLT#3]
请问能把您配置好的vot-toolkit发我一份吗？我运行一直不成功。

**Comment by feidasheng** [comment]
请问你解决了么，我这里测vot的数据集应该放哪呀？

**Comment by eilo1234** [comment]
> 请问你解决了么，我这里测vot的数据集应该放哪呀？

workspace_load.m文件下第142行的文件路径换成你的VOT数据集路径。可能还需要自己写一个list.txt文件。

**Comment by eilo1234** [comment]
&nbsp;
workspace_load.m文件下第142行的文件路径换成你的VOT数据集路径。可能还需要自己写一个list.txt文件。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"feidasheng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 晚上8:13
收件人:&nbsp;"iiau-tracker/SPLT"<SPLT@noreply.github.com&gt;;
抄送:&nbsp;"Eilo"<1812712909@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iiau-tracker/SPLT] vot-toolkit ? (#3)




请问你解决了么，我这里测vot的数据集应该放哪呀？

**Comment by 97-tianyan** [comment]
hello！where is   workspace_load.m ??
this is my error `Traceback (most recent call last):
  File "RPN_Verifier_Skim_top3.py", line 822, in <module>
    handle = vot.VOT("rectangle")
  File "/home/zhutianhao/SPLT/vot.py", line 105, in __init__
    self._files = [x.strip('\n') for x in open('images.txt', 'r').readlines()]
IOError: [Errno 2] No such file or directory: 'images.txt'
(SPLT) zhutianhao@amax:~/SPLT$
`

**Comment by 97-tianyan** [comment]
> ＆nbsp; workspace_load.m文件下第142行的文件路径换成你的VOT数据集路径。可能还需要自己写一个list.txt文件。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"feidasheng"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月1日(星期五) 晚上8:13 收件人:&nbsp;"iiau-tracker/SPLT"<SPLT@noreply.github.com&gt;; 抄送:&nbsp;"Eilo"<1812712909@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [iiau-tracker/SPLT] vot-toolkit ? (#3) 请问你解决了么，我这里测vot的数据集应该放哪呀？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hello，where is workspace_load.m?
